version: '3.9'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

x-labels:
  &default-labels
  logging: "promtail"
  logging_jobname: "containerlogs"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: services/api-gateway
    environment:
      - SERVICE_NAME=api-gateway
    ports:
      - 5000:5000
    depends_on:
      - order-service
      - inventory-service
      - payment-service
      - warehouse-service
      - fraud-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  order-service:
    container_name: order-service
    build:
      context: services/order
    environment:
      - SERVICE_NAME=order-service
    depends_on:
      - inventory-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  inventory-service:
    container_name: inventory-service
    build:
      context: services/inventory
    environment:
      - SERVICE_NAME=inventory-service
      - INVENTORY_AVAILABILITY=1000
    depends_on:
      - warehouse-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  warehouse-service:
    container_name: warehouse-service
    build:
      context: services/warehouse
    environment:
      - SERVICE_NAME=warehouse-service
      - INVENTORY_AVAILABILITY=1000
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  payment-service:
    container_name: payment-service
    build:
      context: services/payment
    environment:
      - SERVICE_NAME=payment-service
      - FRAUD_SERVICE_URL=http://fraud-service:5000
    depends_on:
      - fraud-service
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  fraud-service:
    container_name: fraud-service
    build:
      context: services/fraud
    environment:
      - SERVICE_NAME=fraud-service
      - FRAUD_PERCENTAGE=5
      - NOT_FRAUD_PERCENTAGE=95
    networks:
      - traces
    labels: *default-labels
    logging: *default-logging

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./configs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    depends_on:
      - tempo
    networks:
      - traces
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    ports:
      - 3200:3200   # tempo http
      - 9095:9095   # tempo grpc
      - 14268:14268 # jaeger ingest
      - 4318:4318   # otlp http
      - 4317:4317   # otlp grpc
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo-local.yaml
    command: ["-config.file=/etc/tempo-local.yaml"]
    networks:
      - traces
    logging: *default-logging

  promtail:
    image:  grafana/promtail:2.9.7
    container_name: promtail
    volumes:
      - ./configs/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - traces
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.7
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - traces
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - traces
    logging: *default-logging


networks:
  traces:
    name: traces
    driver: bridge
