services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env.test
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data/
